/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.UsersController;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sam
 */
public class ChangePassword extends javax.swing.JDialog {

    UsersController uc = new UsersController();
    private static String user;
    
    /**
     * Creates new form ChangePassword
     */
    public ChangePassword(java.awt.Frame parent, boolean modal, String username) {
        super(parent, modal);
        setDefaultLookAndFeelDecorated(false);
        setIconImage(new ImageIcon(MainAdmin.class.getResource("images/i16x16/invoice.png")).getImage());
        user = username;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_old = new javax.swing.JLabel();
        txt_old = new javax.swing.JPasswordField();
        lbl_new = new javax.swing.JLabel();
        txt_new = new javax.swing.JPasswordField();
        lbl_confirm = new javax.swing.JLabel();
        txt_confirm = new javax.swing.JPasswordField();
        btn_change = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change password");
        setLocationByPlatform(true);
        setModal(true);
        setResizable(false);

        lbl_old.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        lbl_old.setText("Old password :");

        txt_old.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N

        lbl_new.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        lbl_new.setText("New password :");

        txt_new.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N

        lbl_confirm.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        lbl_confirm.setText("Confirm password :");

        txt_confirm.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N

        btn_change.setText("Change");
        btn_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changeActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btn_change)
                .addGap(87, 87, 87)
                .addComponent(btn_cancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_old)
                    .addComponent(lbl_confirm)
                    .addComponent(lbl_new))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_new, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_old, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_old)
                    .addComponent(txt_old, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_new)
                    .addComponent(txt_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_confirm)
                    .addComponent(txt_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_change)
                    .addComponent(btn_cancel))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changeActionPerformed
        String old = txt_old.getText();
        String newpass = txt_new.getText();
        String confirm = txt_confirm.getText();

        if(!newpass.equals(confirm)){
            JOptionPane.showMessageDialog(null, "Passwords do not match","Error",JOptionPane.ERROR_MESSAGE);
            txt_new.setText(null);
            txt_confirm.setText(null);
        }
        else{
            uc.getUsers().setUsername(user);
            uc.getUsers().setPassword(old);
            int i = uc.changepass(newpass);
            if(i == 0){
                JOptionPane.showMessageDialog(null, "Password incorrect","Error",JOptionPane.ERROR_MESSAGE);
                txt_old.setText(null);
                txt_new.setText(null);
                txt_confirm.setText(null);
                txt_old.grabFocus();
            }
            else if(i == 1){
                JOptionPane.showMessageDialog(null, "Password changed","Success",JOptionPane.PLAIN_MESSAGE);
                dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Can't change password","Error",JOptionPane.ERROR_MESSAGE);
                txt_old.setText(null);
                txt_new.setText(null);
                txt_confirm.setText(null);
                txt_old.grabFocus();
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_changeActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChangePassword dialog = new ChangePassword(new javax.swing.JFrame(), true, user);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_change;
    private javax.swing.JLabel lbl_confirm;
    private javax.swing.JLabel lbl_new;
    private javax.swing.JLabel lbl_old;
    private javax.swing.JPasswordField txt_confirm;
    private javax.swing.JPasswordField txt_new;
    private javax.swing.JPasswordField txt_old;
    // End of variables declaration//GEN-END:variables
}
