/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DepartmentController;
import Controller.Desig_SalaryController;
import Controller.EmployeesController;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sam
 */
public class EditEmployee extends javax.swing.JDialog {

    DepartmentController dc = new DepartmentController();
    Desig_SalaryController dsc = new Desig_SalaryController();
    EmployeesController ec = new EmployeesController();
    Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
    
    private static String emp_ID;
    
    /**
     * Creates new form EditEmployee
     */
    public EditEmployee(java.awt.Frame parent, boolean modal, String ID) {
        super(parent, modal);
        setIconImage(new ImageIcon(LogDetails.class.getResource("images/i16x16/users rec.png")).getImage());
        setLocation(screen.width/4, screen.height/10);
        setDefaultLookAndFeelDecorated(false);
        
        emp_ID = ID;
        ec.getEmployees().setEmp_ID(emp_ID);
        ec.setEmployees(ec.get_details());
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_EmpID = new javax.swing.JLabel();
        txt_EmpID = new javax.swing.JFormattedTextField();
        lbl_FirstName = new javax.swing.JLabel();
        txt_FirstName = new javax.swing.JTextField();
        lbl_MiddleName = new javax.swing.JLabel();
        txt_MiddleName = new javax.swing.JTextField();
        lbl_LastName = new javax.swing.JLabel();
        txt_LastName = new javax.swing.JTextField();
        lbl_DOB = new javax.swing.JLabel();
        txt_DOB = new javax.swing.JFormattedTextField();
        lbl_HireDate = new javax.swing.JLabel();
        txt_hire = new javax.swing.JFormattedTextField();
        lbl_Dept = new javax.swing.JLabel();
        cmb_Dept = new javax.swing.JComboBox();
        lbl_Designation = new javax.swing.JLabel();
        cmb_Designation = new javax.swing.JComboBox();
        lbl_City = new javax.swing.JLabel();
        txt_City = new javax.swing.JTextField();
        lbl_PhoneNo = new javax.swing.JLabel();
        txt_PhoneNo = new javax.swing.JFormattedTextField();
        lbl_EmailID = new javax.swing.JLabel();
        txt_EmailID = new javax.swing.JTextField();
        btn_Update = new javax.swing.JButton();
        btn_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Employee");
        setModal(true);
        setResizable(false);

        lbl_EmpID.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_EmpID.setText("Employee ID :");

        txt_EmpID.setEditable(false);
        txt_EmpID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txt_EmpID.setToolTipText("Enter unique 4 digit");
        txt_EmpID.setText(ec.getEmployees().getEmp_ID());

        lbl_FirstName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_FirstName.setText("First Name :");

        txt_FirstName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_FirstName.setText(ec.getEmployees().getFirst_name());

        lbl_MiddleName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_MiddleName.setText("Middle Name :");

        txt_MiddleName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_MiddleName.setText(ec.getEmployees().getMiddle_name());

        lbl_LastName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_LastName.setText("Last Name :");

        txt_LastName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_LastName.setText(ec.getEmployees().getLast_name());

        lbl_DOB.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_DOB.setText("Date of Birth :");

        txt_DOB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/MM/dd"))));
        txt_DOB.setToolTipText("yyyy/mm/dd");
        txt_DOB.setText(ec.getEmployees().getDob());

        lbl_HireDate.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_HireDate.setText("Hire Date :");

        txt_hire.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/MM/dd"))));
        txt_hire.setToolTipText("yyyy/mm/dd");
        txt_hire.setText(ec.getEmployees().getHire_date());

        lbl_Dept.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_Dept.setText("Department :");

        cmb_Dept.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmb_Dept.setModel(dept());
        cmb_Dept.setToolTipText("To add new department go to \n>>Tools\n>>Manage Department");
        cmb_Dept.setSelectedItem(ec.getEmployees().getDept_name());

        lbl_Designation.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_Designation.setText("Designation :");

        cmb_Designation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmb_Designation.setModel(desig());
        cmb_Designation.setToolTipText("To add new department go to \n>>Tools\n>>Manage Designation");
        cmb_Designation.setSelectedItem(ec.getEmployees().getDesignation());

        lbl_City.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_City.setText("City :");

        txt_City.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_City.setText(ec.getEmployees().getCity());

        lbl_PhoneNo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_PhoneNo.setText("Phone No :");

        txt_PhoneNo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txt_PhoneNo.setText(ec.getEmployees().getPhone_no());

        lbl_EmailID.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_EmailID.setText("Email ID :");

        txt_EmailID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_EmailID.setText(ec.getEmployees().getEmail_ID());

        btn_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/reset.png"))); // NOI18N
        btn_Update.setText("Update");
        btn_Update.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/reset_Hover.png"))); // NOI18N
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        btn_Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/exit.png"))); // NOI18N
        btn_Cancel.setText("Cancel");
        btn_Cancel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/exit_Hover.png"))); // NOI18N
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btn_Update)
                        .addGap(109, 109, 109)
                        .addComponent(btn_Cancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_City)
                                    .addComponent(lbl_PhoneNo)
                                    .addComponent(lbl_EmailID))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_City)
                                    .addComponent(txt_EmailID)
                                    .addComponent(txt_PhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_FirstName)
                                    .addComponent(lbl_MiddleName)
                                    .addComponent(lbl_LastName)
                                    .addComponent(lbl_DOB)
                                    .addComponent(lbl_HireDate)
                                    .addComponent(lbl_Dept)
                                    .addComponent(lbl_Designation)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(lbl_EmpID)))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmb_Designation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_LastName)
                                    .addComponent(txt_MiddleName)
                                    .addComponent(txt_FirstName)
                                    .addComponent(txt_DOB)
                                    .addComponent(txt_hire)
                                    .addComponent(cmb_Dept, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_EmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Cancel, btn_Update});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_EmpID)
                    .addComponent(txt_EmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_FirstName)
                    .addComponent(txt_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MiddleName)
                    .addComponent(txt_MiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_LastName)
                    .addComponent(txt_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_DOB)
                    .addComponent(txt_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_HireDate)
                    .addComponent(txt_hire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Dept)
                    .addComponent(cmb_Dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Designation)
                    .addComponent(cmb_Designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_City)
                    .addComponent(txt_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_PhoneNo)
                    .addComponent(txt_PhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_EmailID)
                    .addComponent(txt_EmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Update)
                    .addComponent(btn_Cancel))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        String City = txt_City.getText();
        String DOB = txt_DOB.getText();
        String Dept = (String)cmb_Dept.getSelectedItem();
        String Designation = (String)cmb_Designation.getSelectedItem();
        String EmailID = txt_EmailID.getText();
        String EmpID = txt_EmpID.getText();
        String FirstName = txt_FirstName.getText();
        String HireDate = txt_hire.getText();
        String LastName = txt_LastName.getText();
        String MiddleName = txt_MiddleName.getText();
        String PhoneNo = txt_PhoneNo.getText();
        
        if("".equals(City)||"".equals(DOB)||"".equals(Dept)||"".equals(Designation)||
                "".equals(EmailID)||"".equals(FirstName)||"".equals(HireDate)||
                "".equals(LastName)||"".equals(PhoneNo)){
            JOptionPane.showMessageDialog(null, "Do not leave fields empty","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            ec.getEmployees().setEmp_ID(EmpID);
            ec.getEmployees().setCity(City);
            ec.getEmployees().setDesignation(Designation);
            ec.getEmployees().setDob(DOB);
            ec.getEmployees().setEmail_ID(EmailID);
            ec.getEmployees().setFirst_name(FirstName);
            ec.getEmployees().setHire_date(HireDate);
            ec.getEmployees().setLast_name(LastName);
            ec.getEmployees().setMiddle_name(MiddleName);
            ec.getEmployees().setPhone_no(PhoneNo);
            ec.getEmployees().setDept_name(Dept);
            
            int i = ec.update();
            if(i == 0){
                JOptionPane.showMessageDialog(null, "ID already used","Error",JOptionPane.ERROR_MESSAGE);
            }
            else if(i == 1){
                JOptionPane.showMessageDialog(null, "Employee Info edited","Success",JOptionPane.PLAIN_MESSAGE);
                dispose();
            }
            else {
                JOptionPane.showMessageDialog(null, "Database problem","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditEmployee dialog = new EditEmployee(new javax.swing.JFrame(), true, emp_ID);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Update;
    private javax.swing.JComboBox cmb_Dept;
    private javax.swing.JComboBox cmb_Designation;
    private javax.swing.JLabel lbl_City;
    private javax.swing.JLabel lbl_DOB;
    private javax.swing.JLabel lbl_Dept;
    private javax.swing.JLabel lbl_Designation;
    private javax.swing.JLabel lbl_EmailID;
    private javax.swing.JLabel lbl_EmpID;
    private javax.swing.JLabel lbl_FirstName;
    private javax.swing.JLabel lbl_HireDate;
    private javax.swing.JLabel lbl_LastName;
    private javax.swing.JLabel lbl_MiddleName;
    private javax.swing.JLabel lbl_PhoneNo;
    private javax.swing.JTextField txt_City;
    private javax.swing.JFormattedTextField txt_DOB;
    private javax.swing.JTextField txt_EmailID;
    private javax.swing.JFormattedTextField txt_EmpID;
    private javax.swing.JTextField txt_FirstName;
    private javax.swing.JTextField txt_LastName;
    private javax.swing.JTextField txt_MiddleName;
    private javax.swing.JFormattedTextField txt_PhoneNo;
    private javax.swing.JFormattedTextField txt_hire;
    // End of variables declaration//GEN-END:variables
    
    private ComboBoxModel desig() {
        DefaultComboBoxModel model = new DefaultComboBoxModel(dsc.get_desig().toArray());
        return model;
    }
    
    private ComboBoxModel dept() {
        DefaultComboBoxModel model = new DefaultComboBoxModel(dc.get_dept().toArray());
        return model;
    }
    
}
