/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.EmployeesController;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class EmployeeDetails extends javax.swing.JDialog {

    EmployeesController ec = new EmployeesController();
    Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
    /**
     * Creates new form EmployeeDetails
     */
    public EmployeeDetails(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setDefaultLookAndFeelDecorated(false);
        setIconImage(new ImageIcon(LogDetails.class.getResource("images/i16x16/employees.png")).getImage());
        setLocation(screen.width/4, screen.height/4);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JSP_Emptbl = new javax.swing.JScrollPane();
        tbl_Log = new javax.swing.JTable();
        btn_Add = new javax.swing.JButton();
        btn_Edit = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        btn_Close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employee Details");
        setModal(true);
        setName("EmployeeDetails"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        JSP_Emptbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        tbl_Log.setAutoCreateRowSorter(true);
        tbl_Log.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl_Log.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tbl_Log.setModel(ec.emp_info());
        tbl_Log.setFillsViewportHeight(true);
        JSP_Emptbl.setViewportView(tbl_Log);

        btn_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/save_all.png"))); // NOI18N
        btn_Add.setText("Add");
        btn_Add.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/save_all_hover.png"))); // NOI18N
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        btn_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/reset.png"))); // NOI18N
        btn_Edit.setText("Edit");
        btn_Edit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/reset_Hover.png"))); // NOI18N
        btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditActionPerformed(evt);
            }
        });

        btn_Delete.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btn_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/i16x16/delete.png"))); // NOI18N
        btn_Delete.setText("Delete");
        btn_Delete.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/i16x16/delete_Hover.png"))); // NOI18N
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        btn_Close.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btn_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/exit.png"))); // NOI18N
        btn_Close.setText("Close");
        btn_Close.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/exit_Hover.png"))); // NOI18N
        btn_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JSP_Emptbl, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btn_Add)
                        .addGap(70, 70, 70)
                        .addComponent(btn_Edit)
                        .addGap(70, 70, 70)
                        .addComponent(btn_Delete)
                        .addGap(70, 70, 70)
                        .addComponent(btn_Close)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Add, btn_Close, btn_Delete, btn_Edit});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JSP_Emptbl, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Close)
                    .addComponent(btn_Delete)
                    .addComponent(btn_Add)
                    .addComponent(btn_Edit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        String column = tbl_Log.getColumnName(tbl_Log.getSelectedColumn());
        if(tbl_Log.getSelectedRow()==-1||!"emp_ID".equals(column)){
            JOptionPane.showMessageDialog(null, "Please select emp_ID first","Error",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            String emp_ID = (String)tbl_Log.getValueAt(tbl_Log.getSelectedRow(), tbl_Log.getSelectedColumn());
            ec.getEmployees().setEmp_ID(emp_ID);
            int reply = JOptionPane.showConfirmDialog(null,"Confirm Delete?","Delete employee",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION){
                int i = ec.delete();
                if(i == 0){
                    JOptionPane.showMessageDialog(null, "This user can't be deleted","Error",JOptionPane.ERROR_MESSAGE);
                }
                else if(i == 1){
                    JOptionPane.showMessageDialog(null, "Employee deleted","Success",JOptionPane.PLAIN_MESSAGE);
                    dispose();
                    EmployeeDetails ed = new EmployeeDetails(null, true);
                    ed.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Deletion error","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        dispose();
        EmployeeDetails ed = new EmployeeDetails(null, true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btn_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CloseActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CloseActionPerformed

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        AddNewEmployee addNewEmployeeMenu = new AddNewEmployee(null, true);
        addNewEmployeeMenu.setVisible(true);
        dispose();
        EmployeeDetails ed = new EmployeeDetails(null, true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditActionPerformed
        String column = tbl_Log.getColumnName(tbl_Log.getSelectedColumn());
        if(tbl_Log.getSelectedRow()==-1||!"emp_ID".equals(column)){
            JOptionPane.showMessageDialog(null, "Please select emp_ID first","Error",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            String emp_ID = (String)tbl_Log.getValueAt(tbl_Log.getSelectedRow(), tbl_Log.getSelectedColumn());
            //JOptionPane.showMessageDialog(null, emp_ID);
            EditEmployee editEmployee = new EditEmployee(null,true,emp_ID);
            editEmployee.setVisible(true);
        }
        dispose();
        EmployeeDetails ed = new EmployeeDetails(null, true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                EmployeeDetails dialog = new EmployeeDetails(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JSP_Emptbl;
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Close;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Edit;
    private javax.swing.JTable tbl_Log;
    // End of variables declaration//GEN-END:variables
}
