/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LogDetailsController;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sam
 */
public class MainUser extends javax.swing.JFrame {

    LogDetailsController ldc = new LogDetailsController();
    Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
    //EmployeesController ec = new EmployeesController();
    
    private String Username;
    private String Type;
    
    public static String curr_dt(){
        Date dt = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String currentTime = sdf.format(dt);
        return currentTime;
    }
    
    /**
     * Creates new form KeeperMain
     */
    public MainUser() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    MainUser(String user, String type) {
        Username = user;
        Type = type;
        ldc.getLogDetails().setUsername(Username);
        ldc.setlogin();
        setDefaultLookAndFeelDecorated(false);
        setIconImage(new ImageIcon(MainAdmin.class.getResource("images/i16x16/employees.png")).getImage());
        setLocation((screen.width - 500) / 2, ((screen.height - 300) / 2) - 70);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane = new javax.swing.JTabbedPane();
        Attendance = new javax.swing.JPanel();
        btn_recordatt = new javax.swing.JButton();
        btn_viewatt = new javax.swing.JButton();
        Salary = new javax.swing.JPanel();
        btn_payslip = new javax.swing.JButton();
        Manage = new javax.swing.JPanel();
        btn_logout = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_changepass = new javax.swing.JButton();
        lbl_usericon = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        lbl_timelogin = new javax.swing.JLabel();
        lbl_logicon = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Keep Attendance");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pane.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pane.setMinimumSize(new java.awt.Dimension(154, 63));

        Attendance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btn_recordatt.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        btn_recordatt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/i32x32/Attendance.png"))); // NOI18N
        btn_recordatt.setText("Record");
        btn_recordatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recordattActionPerformed(evt);
            }
        });

        btn_viewatt.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        btn_viewatt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/i32x32/Advances.png"))); // NOI18N
        btn_viewatt.setText("View");
        btn_viewatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewattActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AttendanceLayout = new javax.swing.GroupLayout(Attendance);
        Attendance.setLayout(AttendanceLayout);
        AttendanceLayout.setHorizontalGroup(
            AttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendanceLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btn_recordatt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btn_viewatt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        AttendanceLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_recordatt, btn_viewatt});

        AttendanceLayout.setVerticalGroup(
            AttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendanceLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(AttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_recordatt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_viewatt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        AttendanceLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_recordatt, btn_viewatt});

        pane.addTab("Attendance", new javax.swing.ImageIcon(getClass().getResource("/View/images/i16x16/Attendance.png")), Attendance); // NOI18N
        Attendance.getAccessibleContext().setAccessibleName("");

        btn_payslip.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        btn_payslip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/i32x32/PaySlip.png"))); // NOI18N
        btn_payslip.setText("Generate Payslip");
        btn_payslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_payslipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SalaryLayout = new javax.swing.GroupLayout(Salary);
        Salary.setLayout(SalaryLayout);
        SalaryLayout.setHorizontalGroup(
            SalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SalaryLayout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(btn_payslip)
                .addGap(134, 134, 134))
        );
        SalaryLayout.setVerticalGroup(
            SalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalaryLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btn_payslip, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pane.addTab("Salary", new javax.swing.ImageIcon(getClass().getResource("/View/images/i16x16/PaySlip.png")), Salary); // NOI18N

        btn_logout.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/i32x32/customers w credits.png"))); // NOI18N
        btn_logout.setText("Log out");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btn_exit.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/i32x32/close.png"))); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_changepass.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        btn_changepass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/i32x32/invoice.png"))); // NOI18N
        btn_changepass.setText("Change Password");
        btn_changepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changepassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManageLayout = new javax.swing.GroupLayout(Manage);
        Manage.setLayout(ManageLayout);
        ManageLayout.setHorizontalGroup(
            ManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageLayout.createSequentialGroup()
                .addGroup(ManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManageLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ManageLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btn_changepass)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        ManageLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_exit, btn_logout});

        ManageLayout.setVerticalGroup(
            ManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(ManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btn_changepass, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        ManageLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_exit, btn_logout});

        pane.addTab("Manage", new javax.swing.ImageIcon(getClass().getResource("/View/images/i16x16/logout.png")), Manage); // NOI18N

        lbl_usericon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/log users.png"))); // NOI18N

        lbl_username.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_username.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_username.setText("Username:");
        lbl_username.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_user.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_user.setText(Username);

        lbl_timelogin.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_timelogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_timelogin.setText("TimeLogin:");
        lbl_timelogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_logicon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_logicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/time-login.png"))); // NOI18N

        lbl_time.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_time.setText(curr_dt());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_usericon, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_user)
                .addGap(53, 53, 53)
                .addComponent(lbl_logicon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lbl_timelogin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_time)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_usericon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_logicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_user))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_timelogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_time))
                        .addGap(2, 2, 2))))
        );

        pane.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        ldc.getLogDetails().setLogout(curr_dt());
        ldc.setlogout();
        dispose();
        new LoginScreen().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        exit();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        exit();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_recordattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recordattActionPerformed
        UserView uv = new UserView(this, true, 1, Username);
        uv.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_recordattActionPerformed

    private void btn_viewattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewattActionPerformed
        UserView uv = new UserView(this, true, 2, Username);
        uv.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_viewattActionPerformed

    private void btn_payslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_payslipActionPerformed
        UserView uv = new UserView(this, true, 3, Username);
        uv.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_payslipActionPerformed

    private void btn_changepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changepassActionPerformed
        ChangePassword cp = new ChangePassword(this, true, Username);
        cp.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_changepassActionPerformed
    
    public void exit(){
        int reply = JOptionPane.showConfirmDialog(this,"Are you sure to exit?","Payroll System",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if (reply == JOptionPane.YES_OPTION){
            setVisible(false);
            ldc.getLogDetails().setLogout(curr_dt());
            ldc.setlogout();
            System.exit(0);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUser().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Attendance;
    private javax.swing.JPanel Manage;
    private javax.swing.JPanel Salary;
    private javax.swing.JButton btn_changepass;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_payslip;
    private javax.swing.JButton btn_recordatt;
    private javax.swing.JButton btn_viewatt;
    private javax.swing.JLabel lbl_logicon;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JLabel lbl_timelogin;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JLabel lbl_usericon;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JTabbedPane pane;
    // End of variables declaration//GEN-END:variables
}
