/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.EmployeesController;
import Controller.LogDetailsController;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sam
 */
public class MainAdmin extends javax.swing.JFrame {
    
    LogDetailsController ldc = new LogDetailsController();
    EmployeesController ec = new EmployeesController();
    
    private String Username;
    private String Type;
    
    public static String curr_dt(){
        Date dt = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String currentTime = sdf.format(dt);
        return currentTime;
    }
    
    /**
     * Creates new form MainAdmin
     */
    public MainAdmin(String username, String type) {
        Username = username;
        Type = type;
        ldc.getLogDetails().setUsername(Username);
        ldc.setlogin();
        setDefaultLookAndFeelDecorated(false);
        setIconImage(new ImageIcon(MainAdmin.class.getResource("images/i16x16/Business.png")).getImage());
        
        initComponents();
    }

    private MainAdmin() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JToolBar();
        btn_EmployeeInfo = new javax.swing.JButton();
        btn_Close = new javax.swing.JButton();
        sep1 = new javax.swing.JToolBar.Separator();
        btn_AddNewEmployee = new javax.swing.JButton();
        btn_EditEmployeeInfo = new javax.swing.JButton();
        btn_DeleteEmployee = new javax.swing.JButton();
        sep2 = new javax.swing.JToolBar.Separator();
        btn_Attendance = new javax.swing.JButton();
        btn_Payslip = new javax.swing.JButton();
        bottom = new javax.swing.JPanel();
        panel_Bottom = new javax.swing.JPanel();
        lbl_usericon = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        lbl_logicon = new javax.swing.JLabel();
        lbl_timelogin = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();
        menubar = new javax.swing.JMenuBar();
        menu_File = new javax.swing.JMenu();
        itm_Logout = new javax.swing.JMenuItem();
        sep_File = new javax.swing.JPopupMenu.Separator();
        itm_Exit = new javax.swing.JMenuItem();
        menu_Edit = new javax.swing.JMenu();
        itm_AddNewEmployee = new javax.swing.JMenuItem();
        itm_EditEmployeeInfo = new javax.swing.JMenuItem();
        itm_DeleteEmployeeInfo = new javax.swing.JMenuItem();
        menu_View = new javax.swing.JMenu();
        itm_EmployeeInfo = new javax.swing.JMenuItem();
        itm_LogDetails = new javax.swing.JMenuItem();
        sep_View = new javax.swing.JPopupMenu.Separator();
        itm_AttendanceRecord = new javax.swing.JMenuItem();
        itm_SalaryRecord = new javax.swing.JMenuItem();
        menu_Tools = new javax.swing.JMenu();
        itm_Dept = new javax.swing.JMenuItem();
        itm_Desig = new javax.swing.JMenuItem();
        itm_ChangePass = new javax.swing.JMenuItem();
        sep_Tools1 = new javax.swing.JPopupMenu.Separator();
        itm_Calculator = new javax.swing.JMenuItem();
        itm_Notepad = new javax.swing.JMenuItem();
        menu_Help = new javax.swing.JMenu();
        itm_HelpContents = new javax.swing.JMenuItem();
        itm_KeybordShortcuts = new javax.swing.JMenuItem();
        sep_Help = new javax.swing.JPopupMenu.Separator();
        itm_About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Payroll System");
        setPreferredSize(setWinSize());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        toolbar.setFloatable(false);
        toolbar.setRollover(true);

        btn_EmployeeInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i32x32/employees.png"))); // NOI18N
        btn_EmployeeInfo.setToolTipText("Employee Info");
        btn_EmployeeInfo.setFocusable(false);
        btn_EmployeeInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_EmployeeInfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_EmployeeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmployeeInfoActionPerformed(evt);
            }
        });
        toolbar.add(btn_EmployeeInfo);

        btn_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i32x32/close.png"))); // NOI18N
        btn_Close.setToolTipText("Close");
        btn_Close.setFocusable(false);
        btn_Close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Close.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CloseActionPerformed(evt);
            }
        });
        toolbar.add(btn_Close);
        toolbar.add(sep1);

        btn_AddNewEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i32x32/author.png"))); // NOI18N
        btn_AddNewEmployee.setToolTipText("Add Employee");
        btn_AddNewEmployee.setFocusable(false);
        btn_AddNewEmployee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_AddNewEmployee.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_AddNewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddNewEmployeeActionPerformed(evt);
            }
        });
        toolbar.add(btn_AddNewEmployee);

        btn_EditEmployeeInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i32x32/xemployees.png"))); // NOI18N
        btn_EditEmployeeInfo.setToolTipText("Edit Employee");
        btn_EditEmployeeInfo.setFocusable(false);
        btn_EditEmployeeInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_EditEmployeeInfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_EditEmployeeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditEmployeeInfoActionPerformed(evt);
            }
        });
        toolbar.add(btn_EditEmployeeInfo);

        btn_DeleteEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i32x32/Delete_emp.png"))); // NOI18N
        btn_DeleteEmployee.setToolTipText("Delete Employee");
        btn_DeleteEmployee.setFocusable(false);
        btn_DeleteEmployee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_DeleteEmployee.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_DeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteEmployeeActionPerformed(evt);
            }
        });
        toolbar.add(btn_DeleteEmployee);
        toolbar.add(sep2);

        btn_Attendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i32x32/Attendance.png"))); // NOI18N
        btn_Attendance.setToolTipText("Attendance record");
        btn_Attendance.setFocusable(false);
        btn_Attendance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Attendance.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Attendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AttendanceActionPerformed(evt);
            }
        });
        toolbar.add(btn_Attendance);

        btn_Payslip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i32x32/PaySlip.png"))); // NOI18N
        btn_Payslip.setToolTipText("Salary record");
        btn_Payslip.setFocusable(false);
        btn_Payslip.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Payslip.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Payslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PayslipActionPerformed(evt);
            }
        });
        toolbar.add(btn_Payslip);

        bottom.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panel_Bottom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_usericon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/log users.png"))); // NOI18N

        lbl_username.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_username.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_username.setText("Username:");
        lbl_username.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_user.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_user.setText(Username);

        lbl_logicon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_logicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/time-login.png"))); // NOI18N

        lbl_timelogin.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_timelogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_timelogin.setText("TimeLogin:");
        lbl_timelogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_time.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_time.setText(curr_dt());

        javax.swing.GroupLayout panel_BottomLayout = new javax.swing.GroupLayout(panel_Bottom);
        panel_Bottom.setLayout(panel_BottomLayout);
        panel_BottomLayout.setHorizontalGroup(
            panel_BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BottomLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(lbl_usericon, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_user)
                .addGap(191, 191, 191)
                .addComponent(lbl_logicon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_timelogin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_time)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        panel_BottomLayout.setVerticalGroup(
            panel_BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_usericon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_logicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_user))
            .addGroup(panel_BottomLayout.createSequentialGroup()
                .addGroup(panel_BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_timelogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_time))
                .addGap(2, 2, 2))
        );

        desktop.setBackground(new java.awt.Color(255, 255, 255));
        desktop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        desktop.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);

        javax.swing.GroupLayout bottomLayout = new javax.swing.GroupLayout(bottom);
        bottom.setLayout(bottomLayout);
        bottomLayout.setHorizontalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(desktop)
        );
        bottomLayout.setVerticalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomLayout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Bottom, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menu_File.setMnemonic(KeyEvent.VK_F);
        menu_File.setText("File");

        itm_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/logout.png"))); // NOI18N
        itm_Logout.setText("Logout");
        itm_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_LogoutActionPerformed(evt);
            }
        });
        menu_File.add(itm_Logout);
        menu_File.add(sep_File);

        itm_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        itm_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/exit.png"))); // NOI18N
        itm_Exit.setText("Exit");
        itm_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_ExitActionPerformed(evt);
            }
        });
        menu_File.add(itm_Exit);

        menubar.add(menu_File);

        menu_Edit.setMnemonic(KeyEvent.VK_E);
        menu_Edit.setText("Employee");

        itm_AddNewEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        itm_AddNewEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/author.png"))); // NOI18N
        itm_AddNewEmployee.setText("Add New Employee");
        itm_AddNewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_AddNewEmployeeActionPerformed(evt);
            }
        });
        menu_Edit.add(itm_AddNewEmployee);

        itm_EditEmployeeInfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        itm_EditEmployeeInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/users rec.png"))); // NOI18N
        itm_EditEmployeeInfo.setText("Edit Employee Info");
        itm_EditEmployeeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_EditEmployeeInfoActionPerformed(evt);
            }
        });
        menu_Edit.add(itm_EditEmployeeInfo);

        itm_DeleteEmployeeInfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        itm_DeleteEmployeeInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/delete.png"))); // NOI18N
        itm_DeleteEmployeeInfo.setText("Delete Employee");
        itm_DeleteEmployeeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_DeleteEmployeeInfoActionPerformed(evt);
            }
        });
        menu_Edit.add(itm_DeleteEmployeeInfo);

        menubar.add(menu_Edit);

        menu_View.setMnemonic(KeyEvent.VK_V);
        menu_View.setText("View");

        itm_EmployeeInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/employees.png"))); // NOI18N
        itm_EmployeeInfo.setText("Employee Info");
        itm_EmployeeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_EmployeeInfoActionPerformed(evt);
            }
        });
        menu_View.add(itm_EmployeeInfo);

        itm_LogDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        itm_LogDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/Log Details.png"))); // NOI18N
        itm_LogDetails.setText("LogDetails");
        itm_LogDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_LogDetailsActionPerformed(evt);
            }
        });
        menu_View.add(itm_LogDetails);
        menu_View.add(sep_View);

        itm_AttendanceRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/Attendance.png"))); // NOI18N
        itm_AttendanceRecord.setText("Attendance Record");
        itm_AttendanceRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_AttendanceRecordActionPerformed(evt);
            }
        });
        menu_View.add(itm_AttendanceRecord);

        itm_SalaryRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/Expenses.png"))); // NOI18N
        itm_SalaryRecord.setText("Salary Record");
        itm_SalaryRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_SalaryRecordActionPerformed(evt);
            }
        });
        menu_View.add(itm_SalaryRecord);

        menubar.add(menu_View);

        menu_Tools.setMnemonic(KeyEvent.VK_T);
        menu_Tools.setText("Tools");

        itm_Dept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/i16x16/branch.png"))); // NOI18N
        itm_Dept.setText("Manage Department");
        itm_Dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_DeptActionPerformed(evt);
            }
        });
        menu_Tools.add(itm_Dept);

        itm_Desig.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        itm_Desig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/i16x16/Advances.png"))); // NOI18N
        itm_Desig.setText("Manage Designation");
        itm_Desig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_DesigActionPerformed(evt);
            }
        });
        menu_Tools.add(itm_Desig);

        itm_ChangePass.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        itm_ChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/PaySlip.png"))); // NOI18N
        itm_ChangePass.setText("Change Password");
        itm_ChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_ChangePassActionPerformed(evt);
            }
        });
        menu_Tools.add(itm_ChangePass);
        menu_Tools.add(sep_Tools1);

        itm_Calculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/calc.png"))); // NOI18N
        itm_Calculator.setText("Calculator");
        itm_Calculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_CalculatorActionPerformed(evt);
            }
        });
        menu_Tools.add(itm_Calculator);

        itm_Notepad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/notepad.png"))); // NOI18N
        itm_Notepad.setText("Notepad");
        itm_Notepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_NotepadActionPerformed(evt);
            }
        });
        menu_Tools.add(itm_Notepad);

        menubar.add(menu_Tools);

        menu_Help.setMnemonic(KeyEvent.VK_H);
        menu_Help.setText("Help");

        itm_HelpContents.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        itm_HelpContents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/contents.png"))); // NOI18N
        itm_HelpContents.setText("Help Contents");
        menu_Help.add(itm_HelpContents);

        itm_KeybordShortcuts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/ProdStocks.png"))); // NOI18N
        itm_KeybordShortcuts.setText("Keyboard Shortcuts");
        menu_Help.add(itm_KeybordShortcuts);
        menu_Help.add(sep_Help);

        itm_About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/i16x16/about.png"))); // NOI18N
        itm_About.setText("About");
        menu_Help.add(itm_About);

        menubar.add(menu_Help);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bottom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itm_LogDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_LogDetailsActionPerformed
        LogDetails ldm = new LogDetails(this,true);
        ldm.setVisible(true);
        //desktop.add(logDetailsMenu);
        // TODO add your handling code here:
    }//GEN-LAST:event_itm_LogDetailsActionPerformed

    private void itm_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_LogoutActionPerformed
        ldc.getLogDetails().setLogout(curr_dt());
        ldc.setlogout();
        dispose();
        new LoginScreen().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_itm_LogoutActionPerformed

    private void itm_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_ExitActionPerformed
        ldc.getLogDetails().setLogout(curr_dt());
        ldc.setlogout();
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_itm_ExitActionPerformed

    private void itm_AddNewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_AddNewEmployeeActionPerformed
        add();
        // TODO add your handling code here:
    }//GEN-LAST:event_itm_AddNewEmployeeActionPerformed

    private void btn_EmployeeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmployeeInfoActionPerformed
        emp_info();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EmployeeInfoActionPerformed

    private void btn_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CloseActionPerformed
        ldc.getLogDetails().setLogout(curr_dt());
        ldc.setlogout();
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CloseActionPerformed

    private void btn_AttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AttendanceActionPerformed
        att_record();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AttendanceActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int reply = JOptionPane.showConfirmDialog(this,"Are you sure to exit?","Payroll System",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if (reply == JOptionPane.YES_OPTION){
            setVisible(false);
            ldc.getLogDetails().setLogout(curr_dt());
            ldc.setlogout();
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void itm_DesigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_DesigActionPerformed
        ManageDesig_Salary desig_SalaryMenu = new ManageDesig_Salary(this, true);
        desig_SalaryMenu.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_itm_DesigActionPerformed

    private void itm_DeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_DeptActionPerformed
        ManageDept departmentMenu = new ManageDept(this, true);
        departmentMenu.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_itm_DeptActionPerformed

    private void itm_CalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_CalculatorActionPerformed
        run("Calc.exe");
        // TODO add your handling code here:
    }//GEN-LAST:event_itm_CalculatorActionPerformed

    private void itm_NotepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_NotepadActionPerformed
        run("Notepad.exe");
        // TODO add your handling code here:
    }//GEN-LAST:event_itm_NotepadActionPerformed

    private void itm_EditEmployeeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_EditEmployeeInfoActionPerformed
        edit();
        // TODO add your handling code here:
    }//GEN-LAST:event_itm_EditEmployeeInfoActionPerformed

    private void itm_DeleteEmployeeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_DeleteEmployeeInfoActionPerformed
        delete();
        // TODO add your handling code here:
    }//GEN-LAST:event_itm_DeleteEmployeeInfoActionPerformed

    private void itm_EmployeeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_EmployeeInfoActionPerformed
        emp_info();
        // TODO add your handling code here:
    }//GEN-LAST:event_itm_EmployeeInfoActionPerformed

    private void btn_AddNewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddNewEmployeeActionPerformed
        add();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AddNewEmployeeActionPerformed

    private void btn_EditEmployeeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditEmployeeInfoActionPerformed
        edit();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EditEmployeeInfoActionPerformed

    private void btn_DeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteEmployeeActionPerformed
        delete();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DeleteEmployeeActionPerformed

    private void itm_ChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_ChangePassActionPerformed
        ChangePassword cp = new ChangePassword(this, true, Username);
        cp.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_itm_ChangePassActionPerformed

    private void itm_AttendanceRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_AttendanceRecordActionPerformed
        att_record();
        // TODO add your handling code here:
    }//GEN-LAST:event_itm_AttendanceRecordActionPerformed

    private void itm_SalaryRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_SalaryRecordActionPerformed
        sal_record();
        // TODO add your handling code here:
    }//GEN-LAST:event_itm_SalaryRecordActionPerformed

    private void btn_PayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PayslipActionPerformed
        sal_record();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_PayslipActionPerformed

    public void add(){
        AddNewEmployee anem = new AddNewEmployee(this,true);
        anem.setVisible(true);
    }
    
    public void edit(){
        String emp_ID = JOptionPane.showInputDialog(null, "Enter emp_ID to edit");
        if(emp_ID == null){   
        }
        else{
            ec.getEmployees().setEmp_ID(emp_ID);
            if(ec.find() == 1){
                EditEmployee editEmployee = new EditEmployee(this,true,emp_ID);
                editEmployee.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null,"Wrong emp_ID","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }
    
    public void delete(){
        String emp_ID = JOptionPane.showInputDialog(null, "Enter emp_ID to delete");
        if(emp_ID == null){   
        }
        else{
            ec.getEmployees().setEmp_ID(emp_ID);
            if(ec.find() == 1){
                int reply = JOptionPane.showConfirmDialog(null,"Confirm Delete?","Delete employee",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
                if (reply == JOptionPane.YES_OPTION){
                    int i = ec.delete();
                    if(i == 0){
                        JOptionPane.showMessageDialog(null, "This user can't be deleted","Error",JOptionPane.ERROR_MESSAGE);
                    }
                    else if(i == 1){
                        JOptionPane.showMessageDialog(null, "Employee deleted","Success",JOptionPane.PLAIN_MESSAGE);
                        dispose();
                        EmployeeDetails ed = new EmployeeDetails(null, true);
                        ed.setVisible(true);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Deletion error","Error",JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"Wrong emp_ID","Error",JOptionPane.ERROR_MESSAGE);
            }
        } 
    }
    
    public void emp_info(){
        EmployeeDetails ed = new EmployeeDetails(this,true);
        ed.setVisible(true);
    }
    
    public void run(String exe){
        Runtime rt = Runtime.getRuntime();
        try{
            rt.exec(exe);
        }
        catch(IOException ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Error Found",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void att_record(){
        AttendanceRecord ar = new AttendanceRecord(this, true);
        ar.setVisible(true);
    }
    
    public void sal_record(){
        SalaryRecord sr = new SalaryRecord(this, true);
        sr.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAdmin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottom;
    private javax.swing.JButton btn_AddNewEmployee;
    private javax.swing.JButton btn_Attendance;
    private javax.swing.JButton btn_Close;
    private javax.swing.JButton btn_DeleteEmployee;
    private javax.swing.JButton btn_EditEmployeeInfo;
    private javax.swing.JButton btn_EmployeeInfo;
    private javax.swing.JButton btn_Payslip;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem itm_About;
    private javax.swing.JMenuItem itm_AddNewEmployee;
    private javax.swing.JMenuItem itm_AttendanceRecord;
    private javax.swing.JMenuItem itm_Calculator;
    private javax.swing.JMenuItem itm_ChangePass;
    private javax.swing.JMenuItem itm_DeleteEmployeeInfo;
    private javax.swing.JMenuItem itm_Dept;
    private javax.swing.JMenuItem itm_Desig;
    private javax.swing.JMenuItem itm_EditEmployeeInfo;
    private javax.swing.JMenuItem itm_EmployeeInfo;
    private javax.swing.JMenuItem itm_Exit;
    private javax.swing.JMenuItem itm_HelpContents;
    private javax.swing.JMenuItem itm_KeybordShortcuts;
    private javax.swing.JMenuItem itm_LogDetails;
    private javax.swing.JMenuItem itm_Logout;
    private javax.swing.JMenuItem itm_Notepad;
    private javax.swing.JMenuItem itm_SalaryRecord;
    private javax.swing.JLabel lbl_logicon;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JLabel lbl_timelogin;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JLabel lbl_usericon;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JMenu menu_Edit;
    private javax.swing.JMenu menu_File;
    private javax.swing.JMenu menu_Help;
    private javax.swing.JMenu menu_Tools;
    private javax.swing.JMenu menu_View;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JPanel panel_Bottom;
    private javax.swing.JToolBar.Separator sep1;
    private javax.swing.JToolBar.Separator sep2;
    private javax.swing.JPopupMenu.Separator sep_File;
    private javax.swing.JPopupMenu.Separator sep_Help;
    private javax.swing.JPopupMenu.Separator sep_Tools1;
    private javax.swing.JPopupMenu.Separator sep_View;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables

    private Dimension setWinSize() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        dim.height -= 25;
        return dim;
    }

}
