/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Desig_SalaryController;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Samir
 */
public class ManageDesig_Salary extends javax.swing.JDialog {

    Desig_SalaryController dsc = new Desig_SalaryController();
    Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
    
    /**
     * Creates new form Desig_SalaryMenu
     */
    public ManageDesig_Salary(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setIconImage(new ImageIcon(LogDetails.class.getResource("images/i16x16/Advances.png")).getImage());
        setDefaultLookAndFeelDecorated(false);
        setLocation(screen.width/4, screen.height/4);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        panel = new javax.swing.JPanel();
        lbl_designation = new javax.swing.JLabel();
        cmb_designation = new javax.swing.JComboBox();
        lbl_desigID = new javax.swing.JLabel();
        txt_desigID = new javax.swing.JTextField();
        lbl_basic = new javax.swing.JLabel();
        txt_basic = new javax.swing.JFormattedTextField();
        lbl_allow = new javax.swing.JLabel();
        lbl_allowval = new javax.swing.JLabel();
        lbl_DA = new javax.swing.JLabel();
        chk_DA = new javax.swing.JCheckBox();
        txt_DA = new javax.swing.JFormattedTextField();
        lbl_HRA = new javax.swing.JLabel();
        chk_HRA = new javax.swing.JCheckBox();
        txt_HRA = new javax.swing.JFormattedTextField();
        lbl_TA = new javax.swing.JLabel();
        chk_TA = new javax.swing.JCheckBox();
        txt_TA = new javax.swing.JFormattedTextField();
        lbl_deduct = new javax.swing.JLabel();
        lbl_deductval = new javax.swing.JLabel();
        lbl_GPF = new javax.swing.JLabel();
        chk_GPF = new javax.swing.JCheckBox();
        txt_GPF = new javax.swing.JFormattedTextField();
        lbl_IT = new javax.swing.JLabel();
        chk_IT = new javax.swing.JCheckBox();
        txt_IT = new javax.swing.JFormattedTextField();
        lbl_GIS = new javax.swing.JLabel();
        chk_GIS = new javax.swing.JCheckBox();
        txt_GIS = new javax.swing.JFormattedTextField();
        lbl_holding = new javax.swing.JLabel();
        chk_HLD = new javax.swing.JCheckBox();
        txt_HLD = new javax.swing.JFormattedTextField();
        lbl_LIC = new javax.swing.JLabel();
        chk_LIC = new javax.swing.JCheckBox();
        txt_LIC = new javax.swing.JFormattedTextField();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Designation - Salary Setting");
        setLocationByPlatform(true);
        setModal(true);
        setResizable(false);

        lbl_designation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_designation.setText("Designation: ");

        cmb_designation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmb_designation.setModel(desig());
        cmb_designation.setSelectedItem(null);
        cmb_designation.addItem("Add new...");
        cmb_designation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_designationActionPerformed(evt);
            }
        });

        lbl_desigID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_desigID.setText("Designation ID: ");

        txt_desigID.setEditable(false);
        txt_desigID.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        txt_desigID.setText("default");
        txt_desigID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_desigIDActionPerformed(evt);
            }
        });

        lbl_basic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_basic.setText("Basic Salary: ");

        txt_basic.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        lbl_allow.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_allow.setText("Allowances");

        lbl_allowval.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_allowval.setText("Value in %");

        lbl_DA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_DA.setText("DA Allowance");

        chk_DA.setText("DA");
        chk_DA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_DAActionPerformed(evt);
            }
        });

        txt_DA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        txt_DA.setEnabled(false);

        lbl_HRA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_HRA.setText("HRA Allowance");

        chk_HRA.setText("HRA");
        chk_HRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_HRAActionPerformed(evt);
            }
        });

        txt_HRA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        txt_HRA.setEnabled(false);

        lbl_TA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_TA.setText("TA Allowance");

        chk_TA.setText("TA");
        chk_TA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_TAActionPerformed(evt);
            }
        });

        txt_TA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        txt_TA.setEnabled(false);

        lbl_deduct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_deduct.setText("Deductions");

        lbl_deductval.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_deductval.setText("Value in %");

        lbl_GPF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_GPF.setText("GPF Deduction");

        chk_GPF.setText("GPF");
        chk_GPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_GPFActionPerformed(evt);
            }
        });

        txt_GPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        txt_GPF.setEnabled(false);

        lbl_IT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_IT.setText("IT Deduction");

        chk_IT.setText("IT");
        chk_IT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_ITActionPerformed(evt);
            }
        });

        txt_IT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        txt_IT.setEnabled(false);

        lbl_GIS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_GIS.setText("GIS Deduction");

        chk_GIS.setText("GIS");
        chk_GIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_GISActionPerformed(evt);
            }
        });

        txt_GIS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        txt_GIS.setEnabled(false);

        lbl_holding.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_holding.setText("Holdings");

        chk_HLD.setText("HLD");
        chk_HLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_HLDActionPerformed(evt);
            }
        });

        txt_HLD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        txt_HLD.setEnabled(false);

        lbl_LIC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_LIC.setText("LIC Deduction");

        chk_LIC.setText("LIC");
        chk_LIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_LICActionPerformed(evt);
            }
        });

        txt_LIC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        txt_LIC.setEnabled(false);

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(lbl_designation)
                                .addGap(35, 35, 35)
                                .addComponent(cmb_designation, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_GPF)
                                            .addComponent(lbl_IT)
                                            .addComponent(lbl_GIS))
                                        .addGap(33, 33, 33)
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chk_GPF)
                                            .addComponent(chk_IT)
                                            .addComponent(chk_GIS)))
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_LIC)
                                            .addComponent(lbl_holding))
                                        .addGap(37, 37, 37)
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chk_LIC)
                                            .addComponent(chk_HLD))))
                                .addGap(28, 28, 28)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_GPF, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_IT, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_GIS, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_HLD, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_LIC, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btn_update)
                                .addGap(62, 62, 62)
                                .addComponent(btn_delete)
                                .addGap(56, 56, 56)
                                .addComponent(btn_cancel))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelLayout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(lbl_allow)
                                    .addGap(132, 132, 132)
                                    .addComponent(lbl_allowval))
                                .addGroup(panelLayout.createSequentialGroup()
                                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_TA)
                                        .addComponent(lbl_HRA)
                                        .addComponent(lbl_DA))
                                    .addGap(32, 32, 32)
                                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chk_HRA, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(chk_DA))
                                        .addGroup(panelLayout.createSequentialGroup()
                                            .addComponent(chk_TA)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                            .addComponent(txt_TA, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_DA, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_desigID)
                                        .addComponent(lbl_basic))
                                    .addGap(18, 18, 18)
                                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_desigID, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                        .addComponent(txt_basic)))
                                .addComponent(txt_HRA, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lbl_deduct)
                        .addGap(130, 130, 130)
                        .addComponent(lbl_deductval)))
                .addGap(50, 50, 50))
        );

        panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_cancel, btn_delete, btn_update});

        panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmb_designation, txt_desigID});

        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_designation)
                    .addComponent(cmb_designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_desigID)
                    .addComponent(txt_desigID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_basic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_basic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_allow)
                    .addComponent(lbl_allowval))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(chk_HRA)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chk_DA)
                            .addComponent(lbl_DA)
                            .addComponent(txt_DA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chk_TA)
                            .addComponent(lbl_TA)
                            .addComponent(txt_TA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_HRA)
                    .addComponent(txt_HRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_deduct)
                    .addComponent(lbl_deductval))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_GPF)
                    .addComponent(chk_GPF)
                    .addComponent(txt_GPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_IT)
                    .addComponent(chk_IT)
                    .addComponent(txt_IT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_GIS)
                    .addComponent(chk_GIS)
                    .addComponent(txt_GIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_holding)
                    .addComponent(chk_HLD)
                    .addComponent(txt_HLD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_LIC)
                    .addComponent(chk_LIC)
                    .addComponent(txt_LIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_update)
                    .addComponent(btn_delete)
                    .addComponent(btn_cancel))
                .addGap(32, 32, 32))
        );

        panelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmb_designation, txt_desigID});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void chk_DAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_DAActionPerformed
        if(chk_DA.isSelected()==true) {
            txt_DA.setEnabled(true);
        }
        else
            txt_DA.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_DAActionPerformed

    private void chk_HRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_HRAActionPerformed
        if(chk_HRA.isSelected()==true) {
            txt_HRA.setEnabled(true);
        }
        else
            txt_HRA.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_HRAActionPerformed

    private void chk_TAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_TAActionPerformed
        if(chk_TA.isSelected()==true) {
            txt_TA.setEnabled(true);
        }
        else
            txt_TA.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_TAActionPerformed

    private void chk_GPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_GPFActionPerformed
        if(chk_GPF.isSelected()==true) {
            txt_GPF.setEnabled(true);
        }
        else
            txt_GPF.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_GPFActionPerformed

    private void chk_ITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_ITActionPerformed
        if(chk_IT.isSelected()==true) {
            txt_IT.setEnabled(true);
        }
        else
            txt_IT.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_ITActionPerformed

    private void chk_GISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_GISActionPerformed
        if(chk_GIS.isSelected()==true) {
            txt_GIS.setEnabled(true);
        }
        else
            txt_GIS.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_GISActionPerformed

    private void chk_HLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_HLDActionPerformed
        if(chk_HLD.isSelected()==true) {
            txt_HLD.setEnabled(true);
        }
        else
            txt_HLD.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_HLDActionPerformed

    private void chk_LICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_LICActionPerformed
        if(chk_LIC.isSelected()==true) {
            txt_LIC.setEnabled(true);
        }
        else
            txt_LIC.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_LICActionPerformed

    private void cmb_designationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_designationActionPerformed
        chk_DA.setSelected(false);
        chk_GPF.setSelected(false);
        chk_HLD.setSelected(false);
        chk_HRA.setSelected(false);
        chk_IT.setSelected(false);
        chk_LIC.setSelected(false);
        chk_TA.setSelected(false);
        
        String desig = (String) cmb_designation.getSelectedItem();
        if(desig=="Add new..."){
            String new_desig = JOptionPane.showInputDialog(this,"Enter new designation","New Designation",JOptionPane.PLAIN_MESSAGE);
            if(new_desig == null){
                cmb_designation.setSelectedItem(null);
            }
            else{
                String new_sal = JOptionPane.showInputDialog(this,"Enter new basic salary","Salary",JOptionPane.PLAIN_MESSAGE);
                if(new_sal == null){
                    cmb_designation.setSelectedItem(null);
                }
                else{
                    dsc.getDesig_Salary().setDesignation(new_desig);
                    dsc.getDesig_Salary().setBasic_pay(new_sal);
                    int i = dsc.add();
                    if(i == 0){
                        JOptionPane.showMessageDialog(null, "Designation already exists","Error",JOptionPane.ERROR_MESSAGE);
                    }
                    else if(i == 1){
                        JOptionPane.showMessageDialog(null, "New Designation added.\n For details entry perform update","Success",JOptionPane.PLAIN_MESSAGE);
                        dispose();
                    }
                    else
                        JOptionPane.showMessageDialog(null, "Database problem","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else{
            dsc.getDesig_Salary().setDesignation(desig);
            dsc.setDesig_Salary(dsc.get_details());
            txt_desigID.setText(dsc.getDesig_Salary().getDes_no());
            txt_basic.setText(dsc.getDesig_Salary().getBasic_pay());
            txt_DA.setText(dsc.getDesig_Salary().getDA_allow());
            txt_HRA.setText(dsc.getDesig_Salary().getHRA_allow());
            txt_TA.setText(dsc.getDesig_Salary().getTA_allow());
            txt_GPF.setText(dsc.getDesig_Salary().getGPF_dedu());
            txt_IT.setText(dsc.getDesig_Salary().getIT_dedu());
            txt_GIS.setText(dsc.getDesig_Salary().getGIS_dedu());
            txt_HLD.setText(dsc.getDesig_Salary().getHoldings());
            txt_LIC.setText(dsc.getDesig_Salary().getLIC_dedu());
            if(!"0".equals(txt_DA.getText()))
                chk_DA.setSelected(true);
            if(!"0".equals(txt_GIS.getText()))
                chk_GIS.setSelected(true);
            if(!"0".equals(txt_GPF.getText()))
                chk_GPF.setSelected(true);
            if(!"0".equals(txt_HLD.getText()))
                chk_HLD.setSelected(true);
            if(!"0".equals(txt_HRA.getText()))
                chk_HRA.setSelected(true);
            if(!"0".equals(txt_IT.getText()))
                chk_IT.setSelected(true);
            if(!"0".equals(txt_LIC.getText()))
                chk_LIC.setSelected(true);
            if(!"0".equals(txt_TA.getText()))
                chk_TA.setSelected(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_designationActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        String desig = (String) cmb_designation.getSelectedItem();
        String basic = txt_basic.getText();
        String DA = txt_DA.getText();
        String HRA = txt_HRA.getText();
        String TA = txt_TA.getText();
        String GPF = txt_GPF.getText();
        String IT = txt_IT.getText();
        String GIS = txt_GIS.getText();
        String HLD = txt_HLD.getText();
        String LIC = txt_LIC.getText();
System.out.println(desig + basic+DA+HRA+TA+GPF+IT+GIS+HLD+LIC);        
        dsc.getDesig_Salary().setDes_no(txt_desigID.getText());
        dsc.getDesig_Salary().setDesignation(desig);
        dsc.getDesig_Salary().setBasic_pay(basic);
        dsc.getDesig_Salary().setDA_allow(DA);
        dsc.getDesig_Salary().setHRA_allow(HRA);
        dsc.getDesig_Salary().setTA_allow(TA);
        dsc.getDesig_Salary().setGPF_dedu(GPF);
        dsc.getDesig_Salary().setIT_dedu(IT);
        dsc.getDesig_Salary().setGIS_dedu(GIS);
        dsc.getDesig_Salary().setHoldings(HLD);
        dsc.getDesig_Salary().setLIC_dedu(LIC);
        
        int i = dsc.update();
        if(i == 1){
            JOptionPane.showMessageDialog(null, "Designation updated","Success",JOptionPane.PLAIN_MESSAGE);
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Update Error","Error",JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int reply = JOptionPane.showConfirmDialog(null,"Confirm Delete?","Delete Designation",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION){
                String desig = (String) cmb_designation.getSelectedItem();
                dsc.getDesig_Salary().setDesignation(desig);
                int i = dsc.delete();
                if(i == 0){
                    JOptionPane.showMessageDialog(null, "Employees exist with given designation."
                            + "\nDelete employee or change designation first","Error",JOptionPane.ERROR_MESSAGE);
                }
                else if(i == 1){
                    JOptionPane.showMessageDialog(null, "Designation deleted","Success",JOptionPane.PLAIN_MESSAGE);
                    dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Deletion error","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void txt_desigIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_desigIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_desigIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageDesig_Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageDesig_Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageDesig_Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageDesig_Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ManageDesig_Salary dialog = new ManageDesig_Salary(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.JCheckBox chk_DA;
    private javax.swing.JCheckBox chk_GIS;
    private javax.swing.JCheckBox chk_GPF;
    private javax.swing.JCheckBox chk_HLD;
    private javax.swing.JCheckBox chk_HRA;
    private javax.swing.JCheckBox chk_IT;
    private javax.swing.JCheckBox chk_LIC;
    private javax.swing.JCheckBox chk_TA;
    private javax.swing.JComboBox cmb_designation;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel lbl_DA;
    private javax.swing.JLabel lbl_GIS;
    private javax.swing.JLabel lbl_GPF;
    private javax.swing.JLabel lbl_HRA;
    private javax.swing.JLabel lbl_IT;
    private javax.swing.JLabel lbl_LIC;
    private javax.swing.JLabel lbl_TA;
    private javax.swing.JLabel lbl_allow;
    private javax.swing.JLabel lbl_allowval;
    private javax.swing.JLabel lbl_basic;
    private javax.swing.JLabel lbl_deduct;
    private javax.swing.JLabel lbl_deductval;
    private javax.swing.JLabel lbl_desigID;
    private javax.swing.JLabel lbl_designation;
    private javax.swing.JLabel lbl_holding;
    private javax.swing.JPanel panel;
    private javax.swing.JFormattedTextField txt_DA;
    private javax.swing.JFormattedTextField txt_GIS;
    private javax.swing.JFormattedTextField txt_GPF;
    private javax.swing.JFormattedTextField txt_HLD;
    private javax.swing.JFormattedTextField txt_HRA;
    private javax.swing.JFormattedTextField txt_IT;
    private javax.swing.JFormattedTextField txt_LIC;
    private javax.swing.JFormattedTextField txt_TA;
    private javax.swing.JFormattedTextField txt_basic;
    private javax.swing.JTextField txt_desigID;
    // End of variables declaration//GEN-END:variables

    private ComboBoxModel desig() {
        DefaultComboBoxModel model = new DefaultComboBoxModel(dsc.get_desig().toArray());
        return model;
    }
}
